SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS squish DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE squish;

CREATE TABLE urls (
  id int(11) NOT NULL,
  long_url text NOT NULL,
  short_id varchar(8) NOT NULL,
  hits int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE urls
  ADD PRIMARY KEY (id);


ALTER TABLE urls
  MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
